os:
  - linux
  - osx

language: node_js

node_js:
  - 'node'

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

script:
  - npm run prepublishOnly
after_success:
  - npm run report-coverage
  - npm run deploy-docs
